### ISSUE TITLE
Problems with the file-upload-service.js file

### ISSUE THREAD

**Issue by gshields5541** [ad440-cloud-project/UX-UI#7]
I’m trying to replace a javascript file that has Axios-based upload service with a javascript file that connects to Microsoft Azure blob storage. However, when I tried to test the Vue app, I get a blank screen where the drag/drop interface should be.

Setup Microsoft Azure resource group
Setup Microsoft Azure static web site
Setup Microsoft Azure blob storage account
Setup Microsoft CORS settings within the storage account
This is the original code for the upload service:

// file-upload.service.js

import * as axios from 'axios';

const BASE_URL = 'http://localhost:3001';

function upload(formData) {
    const url = `${BASE_URL}/photos/upload`;
    return axios.post(url, formData)
        // get data
        .then(x => x.data)
        // add url field
        .then(x => x.map(img => Object.assign({},
            img, { url: `${BASE_URL}/images/${img.id}` })));
}

export { upload }
And this is what I've tried to replace it with:

var blobUri = 'https://' + 'STORAGE_ACCOUNT' + '.blob.core.windows.net';
var blobService = AzureStorage.Blob.createBlobServiceWithSas(blobUri, 'SAS_TOKEN');
// If one file has been selected in the HTML file input element
var file = document.getElementById('fileinput').files[0];

var customBlockSize = file.size > 1024 * 1024 * 32 ? 1024 * 1024 * 4 : 1024 * 512;
blobService.singleBlobPutThresholdInBytes = customBlockSize;

var finishedOrError = false;
var speedSummary = blobService.createBlockBlobFromBrowserFile('mycontainer', 
file.name, file, {blockSize : customBlockSize}, function(error, result, response) {
    finishedOrError = true;
    if (error) {
        // Upload blob failed
    } else {
        // Upload successfully
    }
});
refreshProgress();
The expected result would be seeing the drag and drop upload interface. Actual Result: blank screen

ReferenceError: Can't find variable: AzureStorage (Via Safari DevTools) Work Time! 3 hours

**Comment by JLaveta** [comment]
Interesting. The drag and drop interface shows up fine on the live site. Check it out here:

https://ad440-web-app.azurewebsites.net/

I can browse or drag and drop files onto it. The app then says it has uploaded the file, but I can't seem to find it anywhere in the storage account or the webapp, so I'm not sure it's hooked up yet.

**Comment by gshields5541** [comment]
Yes, that what I’m taking about. When I tested, it was with a “fake upload” service. The real upload service has been commented out, but even if it were uncommented, it probably won’t work because it not setup to hook with the blob. I was trying to replace the javascript code in file-upload-service.js with what I’ve read at this web site, but it’s launching a blank screen instead.

Gerald

**Comment by gshields5541** [comment]
Since the issue is part of the API used to connect the front end to the API end, closing the issue.

**Comment by gshields5541** [comment]
Work time: 2 hours.
